### ISSUE TITLE
[INFO] FOSS Explorer

### ISSUE THREAD

**Issue by Wabri** [albertosantagostino/ITAQA-air-quality-aggregator#17]
Ciao!

La tua repository è stata selezionata dalla nostra redazione per il format "FOSS Explorer" di [Schrodinger Hat](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA), una rubrica del nostro talk show riguardo il software development e il mondo open source italiano, e verrà mostrata nella puntata di Martedì 26 Maggio in diretta sul canale [Twitch](https://www.twitch.tv/schrodinger_hat) e [YouTube](https://www.youtube.com/channel/UC1QLLgrGrPmlaFhS0orykCA) alle ore 13.00.

Il tuo lavoro ci è piaciuto molto e speriamo che questo possa aiutare a fornire visibilità al tuo lavoro ;)
Se per te va bene, la includeremo nella nostra top15 bisettimanale!

A presto!

**Comment by albertosantagostino** [comment]
@Wabri 

Ciao! Ovviamente per me va benissimo, anzi, ti ringrazio per i complimenti!
È un progettino iniziato da poco e ancora poco più di un concept, ma mi fa ovviamente piacere che l'abbiate trovato e ritenuto interessante :)
Inoltre, se può interessarti, conto di pubblicare una serie di mini post tecnici correlati su un microblog che ho inaugurato da poco (https://albertosantagostino.github.io/)

Purtroppo non so se sarò in grado di partecipare alla diretta causa impegni lavorativi ma guarderò poi il video sul vostro canale YouTube!

Grazie mille ancora!

**Comment by Wabri** [comment]
Grazie per la disponibilità, faremo una introduzione anche il tuo nuovo blog allora :+1:
